include = ["./**/*.toml"]

[formatting]
align_entries  = true
column_width   = 120
reorder_keys   = false
reorder_arrays = false

[[rule]]
keys = ["dependencies", "dev-dependencies"]

[rule.formatting]
reorder_keys = true
